function getId(id) {
	return document.getElementById(id);
}

function refresh() {
	var lang = (navigator.language || navigator.browserLanguage).toLowerCase();
	if (lang.substring(0,2)=="zh") {
		switch (lang.substring(3)) {
			case "cn":
			case "sg":
				lingo("zh-cn");
				break;
			default:
				lingo("zh-tw");
		}
	}
	else lingo(lang.substring(0,2));
}

function lingo(lang) {
	if (translation[lang]) {
		getId(lang).checked = true;
		for (var id in translation[lang]) {
			if (id=="langName") continue;
			if (id.length==2&&getId(id).nodeName=="TD") getId(id).title = translation[lang][id];
			else getId(id).innerHTML = translation[lang][id];
		}
	}
	else lingo("en");
}

var translation = {
	"zh-cn": {
		"langName":"简体中文",
		"title":"英语音标/字母发音器",
		"name":"英语音标/字母发音器",
		"language":"语言",
		"style":"风格",
		"old":"旧版音标",
		"rp&ga":"全音标",
		"rp":"英式发音(RP)",
		"ga":"美式发音(GA)",
		"consonant":"辅音",
		"vowel":"元音",
		"others":"其他",
		"source":"发音音频来源于Cambridge English Pronouncing Dictionary第16版光盘。",
		"copyright1":"本作品采用",
		"copyright2":"知识共享署名-相同方式共享 3.0 未本地化版本许可协议",
		"copyright3":"进行许可。",
		"PP":"双唇清爆发音",
		"BB":"双唇浊爆发音",
		"TT":"齿龈清爆发音",
		"DD":"齿龈浊爆发音",
		"KK":"软腭清爆发音",
		"GG":"软腭浊爆发音",
		"FF":"唇齿清擦音",
		"VV":"唇齿浊擦音",
		"SS":"齿龈清擦音",
		"ZZ":"齿龈浊擦音",
		"TH":"齿清擦音",
		"DH":"齿浊擦音",
		"SH":"龈后清擦音",
		"ZH":"龈后浊擦音",
		"CH":"龈后清塞擦音",
		"JH":"龈后浊塞擦音",
		"MM":"双唇鼻音",
		"NN":"齿龈鼻音",
		"NG":"软腭鼻音",
		"RR":"齿龈近音",
		"LL":"齿龈边近音",
		"HH":"声门清擦音",
		"JJ":"硬腭近音",
		"WW":"唇软腭浊近音",
		"IH":"近前次高非圆唇元音",
		"EH":"前半高非圆唇元音",
		"AE":"前次低非圆唇元音",
		"AH":"后半低非圆唇元音",
		"OH":"后低圆唇元音",
		"UH":"靠后次高圆唇元音",
		"AX":"央中元音",
		"IY":"长前高非圆唇元音",
		"AA":"长后低非圆唇元音",
		"AO":"长后半低圆唇元音",
		"UW":"长后高圆唇元音",
		"EE":"长央半低非圆唇元音",
		"RH":"齿龈闪音",
		"AM":"卷舌性央中元音",
		"EM":"长卷舌性央半低非圆唇元音",
		"XX":"软腭清擦音",
		"IQ":"前高非圆唇元音",
		"UQ":"后高圆唇元音",
		"11":"重音符号",
		"22":"次重音符号",
		"00":"分音节符号"
	}, 
	"zh-tw": {
		"langName":"繁體中文",
		"title":"英語音標/字母發音器",
		"name":"英語音標/字母發音器",
		"language":"語言",
		"style":"風格",
		"old":"舊版音標",
		"rp&ga":"全音標",
		"rp":"英式發音(RP)",
		"ga":"美式發音(GA)",
		"consonant":"輔音",
		"vowel":"元音",
		"others":"其他",
		"source":"發音音頻來源於Cambridge English Pronouncing Dictionary第16版光盤。",
		"copyright1":"本著作係採用",
		"copyright2":"創用 CC 姓名標示-相同方式分享 3.0 未本地化 授權條款",
		"copyright3":"授權.",
		"PP":"雙脣清爆發音",
		"BB":"雙脣濁爆發音",
		"TT":"齒齦清爆發音",
		"DD":"齒齦濁爆發音",
		"KK":"軟齶清爆發音",
		"GG":"軟齶濁爆發音",
		"FF":"脣齒清擦音",
		"VV":"脣齒濁擦音",
		"SS":"齒齦清擦音",
		"ZZ":"齒齦濁擦音",
		"TH":"齒清擦音",
		"DH":"齒濁擦音",
		"SH":"齦後清擦音",
		"ZH":"齦後濁擦音",
		"CH":"齦後清塞擦音",
		"JH":"齦後濁塞擦音",
		"MM":"雙脣鼻音",
		"NN":"齒齦鼻音",
		"NG":"軟齶鼻音",
		"RR":"齒齦近音",
		"LL":"齒齦邊近音",
		"HH":"聲門清擦音",
		"JJ":"硬齶近音",
		"WW":"脣軟齶濁近音",
		"IH":"近前次高非圓脣元音",
		"EH":"前半高非圓脣元音",
		"AE":"前次低非圓脣元音",
		"AH":"後半低非圓脣元音",
		"OH":"後低圓脣元音",
		"UH":"靠後次高圓脣元音",
		"AX":"央中元音",
		"IY":"長前高非圓脣元音",
		"AA":"長後低非圓脣元音",
		"AO":"長後半低圓脣元音",
		"UW":"長後高圓脣元音",
		"EE":"長央半低非圓脣元音",
		"RH":"齒齦閃音",
		"AM":"捲舌性央中元音",
		"EM":"長捲舌性央半低非圓脣元音",
		"XX":"軟齶清擦音",
		"IQ":"前高非圓脣元音",
		"UQ":"後高圓脣元音",
		"11":"重音符號",
		"22":"次重音符號",
		"00":"分音節符號"
	},
	"en": {
		"langName":"English",
		"title":"IPA & Letters Pronouncer for English",
		"name":"IPA & Letters Pronouncer for English",
		"language":"Language",
		"style":"Style",
		"old":"Old IPA",
		"rp&ga":"Full Chart",
		"rp":"Received Pronunciation (RP)",
		"ga":"General American (GA)",
		"consonant":"Consonants",
		"vowel":"Vowels",
		"others":"Others",
		"source":"The audio files of pronunciation are extracted from the CD of <i>Cambridge English Pronouncing Dictionary, 16th edition</i>.",
		"copyright1":"This work is licensed under a ",
		"copyright2":"Creative Commons Attribution-ShareAlike 3.0 Unported License",
		"copyright3":".",
		"PP":"Voiceless bilabial plosive",
		"BB":"Voiced bilabial plosive",
		"TT":"Voiceless alveolar plosive",
		"DD":"Voiced alveolar plosive",
		"KK":"Voiceless velar plosive",
		"GG":"Voiced velar plosive",
		"FF":"Voiceless labiodental fricative",
		"VV":"Voiced labiodental fricative",
		"SS":"Voiceless alveolar fricative",
		"ZZ":"Voiced alveolar fricative",
		"TH":"Voiceless dental fricative",
		"DH":"Voiced dental fricative",
		"SH":"Voiceless postalveolar fricative",
		"ZH":"Voiced postalveolar fricative",
		"CH":"Voiceless postalveolar affricate",
		"JH":"Voiced postalveolar affricate",
		"MM":"Bilabial nasal",
		"NN":"Alveolar nasal",
		"NG":"Velar nasal",
		"RR":"Alveolar approximant",
		"LL":"Alveolar lateral approximant",
		"HH":"Voiceless glottal fricative",
		"JJ":"Palatal approximant",
		"WW":"Voiced labial-velar approximant",
		"IH":"Near-close near-front unrounded vowel",
		"EH":"Close-mid front unrounded vowel",
		"AE":"Near-open front unrounded vowel",
		"AH":"Open-mid back unrounded vowel",
		"OH":"Open back rounded vowel",
		"UH":"Near-close near-back rounded vowel",
		"AX":"Mid central vowel",
		"IY":"Long close front unrounded vowel",
		"AA":"Long open back unrounded vowel",
		"AO":"Long open-mid back rounded vowel",
		"UW":"Long close back rounded vowel",
		"EE":"Long open-mid central unrounded vowel",
		"RH":"Alveolar Flap",
		"AM":"Rhotic mid central vowel",
		"EM":"Long rhotic open-mid central unrounded vowel",
		"XX":"Voiceless velar fricative",
		"IQ":"Close front unrounded vowel",
		"UQ":"Close back rounded vowel",
		"11":"Primary stress",
		"22":"Secondary stress",
		"00":"Syllable break"
	}
};